import {
  AreaChart as AreaChartIcon,
  AssignmentInd as AssignmentIndIcon,
  AssignmentTurnedInRounded as AssignmentTurnedInRoundedIcon,
  CalendarMonth as CalendarMonthIcon,
  Create as CreateIcon,
  FoodBankRounded as FoodBankRoundedIcon,
  LocalDrink as LocalDrinkIcon,
  ManageAccounts as ManageAccountsIcon,
  ShoppingBasket as ShoppingBasketIcon,
  UploadFileRounded as UploadFileRoundedIcon,
} from "@mui/icons-material";

export const NAVIGATION = [
  {
    segment: "dashboard",
    title: "แดชบอร์ดสถิติ",
    icon: <AreaChartIcon />,
    roles: ["admin", "superadmin"],
    group: "main",
  },
  {
    segment: "calendar",
    title: "ตารางงาน",
    icon: <CalendarMonthIcon />,
    roles: ["admin", "superadmin"],
    group: "main",
  },
  {
    segment: "sales-report",
    title: "รายงานขาย",
    icon: <ShoppingBasketIcon />,
    roles: ["admin", "superadmin"],
    group: "main",
  },
  {
    segment: "sales-day",
    title: "ออเดอร์รายวัน",
    icon: <AssignmentTurnedInRoundedIcon />,
    roles: ["admin", "superadmin"],
    group: "main",
  },
  {
    segment: "user-management",
    title: "จัดการพนักงาน",
    icon: <ManageAccountsIcon />,
    roles: ["admin", "superadmin"],
    group: "upload",
    children: [
      {
        segment: "staff-management",
        title: "อนุมัติพนักงาน",
        icon: <AssignmentIndIcon />,
        roles: ["admin", "superadmin"],
        group: "management",
      },
      // {
      //   segment: "register-admin",
      //   title: "เพิ่มแอดมิน",
      //   icon: <PeopleIcon />,
      //   roles: ["admin", "superadmin"],
      //   group: "management",
      // },
    ],
  },
  {
    segment: "upload-products",
    title: "อัพโหลดสินค้า",
    icon: <UploadFileRoundedIcon />,
    roles: ["admin", "superadmin"],
    group: "upload",
  },
  {
    segment: "dried-category",
    title: "ประเภทแห้ง",
    icon: <FoodBankRoundedIcon />,
    roles: ["admin", "superadmin"],
    group: "product",
  },
  {
    segment: "drink-category",
    title: "ประเภทเครื่องดื่ม",
    icon: <LocalDrinkIcon />,
    roles: ["admin", "superadmin"],
    group: "product",
  },
  // {
  //   segment: "fresh-category",
  //   title: "ประเภทแช่แข็ง",
  //   icon: <AcUnitIcon />,
  //   roles: ["admin", "superadmin"],
  //   group: "product",
  // },
  // {
  //   segment: "snack-category",
  //   title: "ประเภทขนม",
  //   icon: <CookieRoundedIcon />,
  //   roles: ["admin", "superadmin"],
  //   group: "product",
  // },
  {
    segment: "stationery-category",
    title: "ประเภทเครื่องเขียน",
    icon: <CreateIcon />,
    roles: ["admin", "superadmin"],
    group: "product",
  },
];
